<h1><center>Assignment Day14</center></h1>

# 1. Create a 3x3x3 array with random values 

In [1]:

#`hint: np.random.random`
import numpy as np

Z = np.random.random((3,3,3))
print(Z)

[[[0.62255532 0.4592445  0.85787235]
  [0.81837368 0.03780214 0.68233702]
  [0.04356744 0.45659182 0.03988841]]

 [[0.77731032 0.2166435  0.76274882]
  [0.27921621 0.70447047 0.69568571]
  [0.96701927 0.99473295 0.58705527]]

 [[0.44970151 0.11189269 0.81214461]
  [0.22932756 0.87497325 0.59925142]
  [0.64031547 0.63576308 0.78519572]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:

Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [4]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[ 1.57709476  1.49096153  0.81830741 -0.64157242  0.63656125]
 [-0.92212794  0.643355   -1.50444262  0.908978   -0.25946159]
 [ 0.94082386 -0.01699244 -0.35850115 -0.07283823 -0.84990679]
 [-0.68665736 -1.30372775 -1.01103122 -0.74965116  0.31612206]
 [-1.29100168 -1.26145823  0.30065932  1.68992764  1.60657973]]


# 5.  How to find common values between two arrays?

In [5]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 2 5 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-06-29
2021-06-30
2021-07-01


# 7. Consider two random array A and B, check if they are equal

In [7]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.0139116  0.52160629 0.         0.75926326 0.61074782 0.59037025
 0.0290155  0.17929636 0.78415726 0.4637457 ]


# 9. How to print all the values of an array?

In [9]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [10]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y1 = X - X.mean(axis=1).reshape(-1, 1)

print(Y)
print(Y1)

[[ 0.1154591  -0.11857221  0.33685093 -0.04971272 -0.34335015  0.23346032
  -0.02051634 -0.41585279  0.16167161  0.10056224]
 [ 0.53332331 -0.07035807 -0.31011759 -0.21889163  0.02425982 -0.30248973
   0.27839114 -0.14473902  0.4911948  -0.28057304]
 [ 0.58642532 -0.1706655  -0.24577176 -0.04617972  0.17109239  0.45059317
  -0.07838721 -0.13781554 -0.27999885 -0.2492923 ]
 [ 0.3706816  -0.03575518  0.0851519  -0.44538833 -0.03646584  0.33875342
  -0.51557886 -0.50145164  0.37139663  0.36865631]
 [ 0.23557807 -0.31435407  0.17840034  0.22750566 -0.08413483  0.04261425
   0.03133602  0.05208307 -0.22238447 -0.14664404]]
[[ 0.1154591  -0.11857221  0.33685093 -0.04971272 -0.34335015  0.23346032
  -0.02051634 -0.41585279  0.16167161  0.10056224]
 [ 0.53332331 -0.07035807 -0.31011759 -0.21889163  0.02425982 -0.30248973
   0.27839114 -0.14473902  0.4911948  -0.28057304]
 [ 0.58642532 -0.1706655  -0.24577176 -0.04617972  0.17109239  0.45059317
  -0.07838721 -0.13781554 -0.27999885 -0.2492923 ]

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[3. 9. 2. 1. 1. 3. 3. 3. 1. 4.]


In [12]:
np.add.at(Z, I, 1)
print(Z)

[ 5. 17.  3.  1.  1.  5.  5.  5.  1.  7.]


# 12.How to get the diagonal of a dot product?

In [13]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(A)
print(B)
# Slow version
prod1=np.diag(np.dot(A, B))

# Fast version
prod2=np.sum(A * B.T, axis=1)

print("diagonal of a dot product method 1 is....",prod1)
print("diagonal of a dot product method 2 is....",prod2)

[[0.80160504 0.0745288  0.27881314 0.96753207 0.24694868]
 [0.25748138 0.01801309 0.7429138  0.21891607 0.26363187]
 [0.24376775 0.11489932 0.73260901 0.85738095 0.22438106]
 [0.49638701 0.54147449 0.52612158 0.26375411 0.43385127]
 [0.55028967 0.14697009 0.41209323 0.469204   0.59608491]]
[[0.83892742 0.38924361 0.0869511  0.96006728 0.3517637 ]
 [0.50336351 0.86516732 0.83225768 0.00708839 0.06441837]
 [0.27192039 0.71678261 0.09780978 0.90725423 0.16306812]
 [0.73635634 0.96550761 0.64749814 0.37851344 0.56414948]
 [0.92421931 0.8999996  0.69481242 0.91056549 0.8922267 ]]
diagonal of a dot product method 1 is.... [1.72650162 1.09694872 0.89953336 1.45261361 1.06678283]
diagonal of a dot product method 2 is.... [1.72650162 1.09694872 0.89953336 1.45261361 1.06678283]


# 13.How to find the most frequent value in an array?

In [14]:
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[0 9 3 6 3 9 3 8 8 1 9 8 6 4 1 5 5 7 9 6 0 0 1 2 0 6 1 3 1 2 9 3 7 4 8 4 5
 3 9 0 7 4 3 5 7 8 9 9 6 7]
9


# 14.How to get the n largest values of an array

In [15]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5


print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [16]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


<h1><center>Thankyou</center></h1>