<h1><center>Assignment Day25</center></h1>

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
data = pd.read_csv("train.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [4]:
data.dropna(axis=0,inplace=True)

In [5]:
data.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [6]:
data = data.drop(['PassengerId','Name','Ticket','Cabin'], axis=1)

In [7]:
le = LabelEncoder()
data['Sex'] = le.fit_transform(data['Sex'])

In [8]:
data['Embarked'] = le.fit_transform(data['Embarked'])

In [9]:
def Nav_Model(col):
    x = data.drop([col], axis=1)
    y = data[col]
    train_x, test_x, train_y, test_y = train_test_split(x, y, test_size=0.2, random_state = 42)
    model = BernoulliNB()
    model.fit(train_x, train_y)
    ypred = model.predict(test_x)
    print("==================================================================")
    print(f"Accuracy score is {accuracy_score(test_y, ypred)}")
    print("==================================================================")
    print(f"Confusion Matrix: \n{confusion_matrix(test_y, ypred)}")
    print("==================================================================")

Pclass as Dependent Variable

In [10]:
Nav_Model('Pclass')

Accuracy score is 0.8648648648648649
Confusion Matrix: 
[[32  0  0]
 [ 3  0  0]
 [ 2  0  0]]


SibSp as Dependent Variable

In [11]:
Nav_Model('SibSp')

Accuracy score is 0.6216216216216216
Confusion Matrix: 
[[23  0  0]
 [11  0  0]
 [ 3  0  0]]


 Sex as dependent variable

In [12]:
Nav_Model('Sex')

Accuracy score is 0.7567567567567568
Confusion Matrix: 
[[16  2]
 [ 7 12]]


Parch as Dependent variable

In [13]:
Nav_Model('Parch')

Accuracy score is 0.6216216216216216
Confusion Matrix: 
[[23  0  0]
 [11  0  0]
 [ 3  0  0]]


Embarked as Dependent variable

In [14]:
data.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
1          1       1    0  38.0      1      0  71.2833         0
3          1       1    0  35.0      1      0  53.1000         2
6          0       1    1  54.0      0      0  51.8625         2
10         1       3    0   4.0      1      1  16.7000         2
11         1       1    0  58.0      0      0  26.5500         2

In [15]:
Nav_Model('Embarked')

Accuracy score is 0.5135135135135135
Confusion Matrix: 
[[ 0 18]
 [ 0 19]]


<h1><center>Thankyou</center></h1>